### ISSUE TITLE
VictoriaTraces: OTLP Ingestion API and Jaeger Query APIs, and Project Introduction

### ISSUE THREAD

**Issue by jiekun** [VictoriaMetrics/VictoriaTraces#1]
### Is your feature request related to a problem? Please describe

> Note: This issue was updated on Jul 6. Previously, it aimed to be a proof of concept to see if VictoriaLogs could serve as distributed tracing storage.

Based on the results of the PoC, VictoriaLogs can be used as the storage for distributed tracing. 

It's good to have VictoriaTraces and support popular ingestion and query protocols.

### Describe the solution you'd like

Currently, the OpenTelemetry Protocol (OTLP) is one of the most widely used protocols for transmitting trace data. Jaeger and Grafana Tempo are also popular in the ecosystem. We can start by supporting these protocols.

### Milestones

Higher Priority:
- [x] Add support for OTLP data ingestion.
- [x] Add support for Jaeger query APIs.
- [ ] https://github.com/VictoriaMetrics/VictoriaTraces/issues/5
- [x] https://github.com/VictoriaMetrics/VictoriaTraces/issues/4
- [ ] Separate VictoriaTraces into a standalone repository.

Lower Priority:
- [ ] https://github.com/VictoriaMetrics/helm-charts/issues/2248
- [ ] https://github.com/VictoriaMetrics/operator/issues/1407 
- [ ] https://github.com/VictoriaMetrics/VictoriaTraces/issues/6
- [ ] https://github.com/VictoriaMetrics/VictoriaTraces/issues/2

**Comment by possibull** [comment]
After cloning Jaeger repository make sure to check-out branch `release-1.35`
and 
```
git submodule update --init --recursive
```
When running the docker command to run Jaeger also specify 1.35 as version
```
docker run -d -p6831:6831/udp -p16686:16686 jaegertracing/all-in-one:1.35
```

**Comment by possibull** [comment]
To configure docker image to work with gRPC remote storage see below:

```
docker run \
  -e SPAN_STORAGE_TYPE=grpc-plugin \
  -e GRPC_STORAGE_SERVER=<...> \
  -p6831:6831/udp -p16686:16686 \
  jaegertracing/all-in-one:1.35
```
https://www.jaegertracing.io/docs/1.65/deployment/#remote-storage

**Comment by possibull** [comment]
With the latest branch I was able to get`SpanWriterPluginServer.WriteSpan()` working

there is some type of issue with protobuf on the reader

but I am getting these errors on make check-all
```
# github.com/VictoriaMetrics/VictoriaMetrics/app/vlinsert/jaeger
app/vlinsert/jaeger/span_writer_plugin_server.go:62:3: github.com/VictoriaMetrics/VictoriaMetrics/lib/logstorage.Field struct literal uses unkeyed fields
app/vlinsert/jaeger/span_writer_plugin_server.go:63:3: github.com/VictoriaMetrics/VictoriaMetrics/lib/logstorage.Field struct literal uses unkeyed fields
make: *** [vet] Error 1
```

**Comment by possibull** [comment]
Fixed the above un-keyed errors and a copy/paste mistake in latest branch.  `SpanWriterPlugin` now is operating correctly.

Some challenges in `SpanReaderPlugin` are the following:
- How we execute the query - we could either create an HttpRequest and populate it and run it through like a normal query or we could call the query functions directly
- Should we move code for the plugins to `app/victoria-logs` write now they are in `app/vlinsert` which works for `SpanWriterPlugin` but not so much for `SpanReaderPlugin`

Either way we need to implement all of the functions in `span_reader_plugin.go`

**Comment by jiekun** [comment]
Hi!

> How we execute the query - we could either create an HttpRequest and populate it and run it through like a normal query or we could call the query functions directly

I assume it's about how to test them, or how to call those function without jaeger? If so, I added a test client in the latest commit (please `git pull`).

If it's about how to run query within VictoriaLogs, you could check [this function](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/42c21ff67128d4d2e2c3f2fe7c787c06a863e187/app/vlselect/logsql/logsql.go#L898-L914). Basically, we may need to:
1. construct a `*logstorage.Query` argument.
2. call `vlstorage.RunQuery`.

This part could be complex if you haven't checked the query execution of VictoriaLogs. I would recommend executing any query in the VMUI (e.g.: `*`) and add a break point to do single step debugging. You can also leave this part to me.

> Should we move code for the plugins to app/victoria-logs write now they are in app/vlinsert which works for SpanWriterPlugin but not so much for SpanReaderPlugin

Good catch! The reader plugin should be moved to `app/vlselect`. Additionally, the `jaeger/proto` folder should be relocated to a shared public directory accessible by both the reader and writer. Perhaps `./lib` would be a suitable option. as a example, we have `lib/prompbmarshal/remote.pb.go`.

**Comment by jiekun** [comment]
I updated the poc branch which should be runnable along with the following docker compose:

<details>

```yaml
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.60.0
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - SPAN_STORAGE_TYPE=grpc
      - GRPC_STORAGE_SERVER=127.0.0.1:17271
    network_mode: "host"
  hotrod:
    image: dockerproxy.net/jaegertracing/example-hotrod:latest
    # To run the latest trunk build, find the tag at Docker Hub and use the line below
    # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
    #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
    ports:
      - "8080:8080"
    command: ["all"]
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
    network_mode: "host"
```

</details>

There are few issues remain unsolved now:
1. `GetTrace` API will panic when receiving request. It's because the income data does not match the data type defined in `pb.go` (`model.TraceID`, to be specific).
2. Duration filter is not working. I think [the range filter](https://docs.victoriametrics.com/victorialogs/logsql/#range-filter) should be the correct way to go but it does not work as expected right now.
3. Some incorrect trace spans (e.g. missing couple letters at the beginning or the end) are ingested.

I think we could start testing and hopefully ingest more data and see if the performance is acceptable.
